### ISSUE TITLE
trying and failing to pull image

### ISSUE THREAD

**Issue by fpcsong** [agileml/examples#5]
**bug描述**
提交任务后等待调度大约6分钟，开始拉取镜像时出现了
```
Error from server (BadRequest): container "pytorch-gpu-job" in pod "data-aug-for-dst-task-multiwoz-0" is waiting to start: trying and failing to pull image

```
使用的任务描述文件内容为：
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: data-aug-for-dst
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "task-multiwoz"
      template:
        metadata:
          name: pytorch-gpu-job
        spec:
          containers:
            - name: pytorch-gpu-job
              image: registry.cn-beijing.aliyuncs.com/iielct/nlp-base:cuda-10.0
              workingDir: '/code/sxh/data_aug_for_dst'
              command: ["./run.sh"]
              resources:
                limits:
                  nvidia.com/gpu: "1"
                requests:
                  nvidia.com/gpu: "1"
              volumeMounts:
              - name: pvc-aijob
                mountPath: "/code"           
          volumes:
            - name: pvc-aijob
              persistentVolumeClaim:
                claimName: pvc-aijob
          restartPolicy: OnFailure
```
